manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v3.7.0
      import:
        # Limit the Zephyr modules to the required set
        name-allowlist:
          - cmsis
          - hal_stm32
          - mbedtls
          - mcuboot
          - picolibc

    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: 1.10.1
