# Place the reboot reason structure in SRAM5 noinit output section
CONFIG_MEMFAULT_REBOOT_TRACKING_REGION="SRAM5"
CONFIG_MEMFAULT_RAM_BACKED_COREDUMP_REGION="SRAM5"

# The SRD SRAM is 32KB in size. Size the coredump storage to fit, leaving a
# little headroom for the reboot tracking data.
CONFIG_MEMFAULT_RAM_BACKED_COREDUMP_SIZE=4096
